language: node_js
node_js:
- 0.10
before_script:
- git config --global user.email "leiguorui@goodow.com"
- git config --global user.name "leiguorui"
- npm install -g bower
script:
- bower install
- gulp
env:
  global:
  - secure: OUoOno46B790w5FM0gtF3MsRj4wonOBHHck7f5gT+5YLSiqyDXjMd39ca35puCNxqKGyIRSQqAuzdprfJsZrA7B/YkeRKQxk8I1mNOpW+t/VQ7d95BruBoJnHFLg6Z+zE7+2Yf8AKtR3AOLdJU+Qn3pXXgFJrsmUf8DFJrguEEk=
